scm
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_000") (PredicateNode "ADORA2A") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_000") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_000") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_001") (PredicateNode "ADRBK2") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_001") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_001") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_002") (AndLink (PredicateNode "A4GALT") (PredicateNode "CHEK2")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_002") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_002") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_003") (AndLink (PredicateNode "ACO2") (PredicateNode "MAPK12")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_003") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_003") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_004") (AndLink (PredicateNode "ADRBK2") (PredicateNode "AP1B1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_004") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_004") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_005") (AndLink (PredicateNode "AIFM3") (PredicateNode "SLC25A17")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_005") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_005") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_006") (AndLink (PredicateNode "AIFM3") (PredicateNode "TMEM184B")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_006") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_006") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_007") (AndLink (PredicateNode "ALG12") (PredicateNode "GGT1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_007") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_007") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_008") (AndLink (PredicateNode "ANKRD54") (PredicateNode "GGA1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_008") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_008") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_009") (AndLink (PredicateNode "APOBEC3C") (PredicateNode "ELFN2")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_009") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_009") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_010") (AndLink (PredicateNode "APOBEC3C") (PredicateNode "KCTD17")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_010") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_010") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_011") (AndLink (PredicateNode "APOBEC3D") (PredicateNode "NCAPH2")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_011") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_011") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_012") (AndLink (PredicateNode "APOBEC3G") (PredicateNode "CRYBB1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_012") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_012") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_013") (AndLink (PredicateNode "APOBEC3G") (PredicateNode "PI4KA")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_013") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_013") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_014") (AndLink (PredicateNode "ARFGAP3") (PredicateNode "RANBP1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_014") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_014") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_015") (AndLink (PredicateNode "ARSA") (PredicateNode "OSM")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_015") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_015") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_016") (AndLink (PredicateNode "ASPHD2") (PredicateNode "LZTR1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_016") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_016") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_017") (AndLink (PredicateNode "ATP5L2") (PredicateNode "TXNRD2")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_017") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_017") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_018") (AndLink (PredicateNode "BIK") (PredicateNode "CRYBB2P1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_018") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_018") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_019") (AndLink (PredicateNode "BRD1") (PredicateNode "MPPED1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_019") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_019") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_020") (AndLink (PredicateNode "C22orf15") (PredicateNode "CACNA1I")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_020") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_020") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_021") (AndLink (PredicateNode "C22orf15") (PredicateNode "ENTHD1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_021") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_021") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_022") (AndLink (PredicateNode "C22orf23") (PredicateNode "UPB1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_022") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_022") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_023") (AndLink (PredicateNode "C22orf31") (PredicateNode "DDX17")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_023") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_023") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_024") (AndLink (PredicateNode "CBX6") (PredicateNode "LARGE")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_024") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_024") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_025") (AndLink (PredicateNode "CBX7") (PredicateNode "MRPL40")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_025") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_025") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_026") (AndLink (PredicateNode "CBX7") (PredicateNode "PIM3")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_026") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_026") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_027") (AndLink (PredicateNode "CBX7") (PredicateNode "SEC14L3")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_027") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_027") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_028") (AndLink (PredicateNode "CCDC117") (PredicateNode "DDX17")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_028") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_028") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_029") (AndLink (PredicateNode "CCDC117") (PredicateNode "NFAM1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_029") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_029") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_030") (AndLink (PredicateNode "CCT8L2") (PredicateNode "PICK1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_030") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_030") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_031") (AndLink (PredicateNode "CDPF1") (PredicateNode "TRABD")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_031") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_031") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_032") (AndLink (PredicateNode "CECR6") (PredicateNode "PPP6R2")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_032") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_032") (PredicateNode "aging")))
