// Custom Atom types for the bio scientist project

GENE_NODE <- CONCEPT_NODE
MOLECULE_NODE <- CONCEPT_NODE

// http://geneontology.org/docs/ontology-documentation/
CELLULAR_COMPONENT_NODE <- CONCEPT_NODE
MOLECULAR_FUNCTION_NODE <- CONCEPT_NODE
BIOLOGICAL_PROCESS_NODE <- CONCEPT_NODE

PATHWAY_NODE <- CONCEPT_NODE
REACTOME_NODE <- PATHWAY_NODE
SMP_NODE <- PATHWAY_NODE

// https://www.ebi.ac.uk/ols/ontologies/uberon
UBERON_NODE <- CONCEPT_NODE
// http://www.obofoundry.org/ontology/cl.html
CELL_NODE <- CONCEPT_NODE

RNA_NODE <- MOLECULE_NODE
// https://www.ebi.ac.uk/chebi/
CHEBI_NODE <- MOLECULE_NODE
// https://www.uniprot.org/
UNIPROT_NODE <- MOLECULE_NODE
// https://pubchem.ncbi.nlm.nih.gov/
PUBCHEM_NODE <- MOLECULE_NODE

// Represents noncoding RNAs
REFSEQ_NODE <- RNA_NODE
// Represents coding RNAs
ENST_NODE <- RNA_NODE
