(define count (count-all))
(define message (string-append " Atoms loaded " "\n"))
(display count)
(display message)
(define start_time (current-time))
(PredicateNode "ANXA7") 
(PredicateNode "ANXA8") 
(PredicateNode "BBIP1") 
(PredicateNode "C10orf10") 
(PredicateNode "C10orf88") 
(PredicateNode "C1QL3") 
(PredicateNode "CCAR1") 
(PredicateNode "COMTD1") 
(PredicateNode "CSTF2T") 
(PredicateNode "DDIT4") 
(PredicateNode "DKK1") 
(PredicateNode "DNAJC12") 
(PredicateNode "DPYSL4") 
(PredicateNode "DYDC1") 
(PredicateNode "EBF3") 
(PredicateNode "EGR2") 
(PredicateNode "FAM35BP") 
(PredicateNode "FAM53B") 
(PredicateNode "FBXW4") 
(PredicateNode "FGF8") 
(PredicateNode "FUOM") 
(PredicateNode "FUT11") 
(PredicateNode "FZD8") 
(PredicateNode "GATA3") 
(PredicateNode "GOT1") 
(PredicateNode "GPR26") 
(PredicateNode "H2AFY2") 
(PredicateNode "HHEX") 
(PredicateNode "HMX2") 
(PredicateNode "HTRA1") 
(PredicateNode "IDE") 
(PredicateNode "IFIT1B") 
(PredicateNode "IKZF5") 
(PredicateNode "ITGB1") 
(PredicateNode "ITPRIP") 
(PredicateNode "JMJD1C.AS1") 
(PredicateNode "KIF11") 
(PredicateNode "KIF5B") 
(PredicateNode "LBX1.AS1") 
(PredicateNode "LGI1") 
(PredicateNode "MAP3K8") 
(PredicateNode "MAPK8") 
(PredicateNode "MCU") 
(PredicateNode "MINPP1") 
(PredicateNode "MYOZ1") 
(PredicateNode "NET1") 
(PredicateNode "PAX2") 
(PredicateNode "PCGF5") 
(PredicateNode "PGAM1") 
(PredicateNode "PI4K2A") 
(PredicateNode "PITX3") 
(PredicateNode "PPP3CB") 
(PredicateNode "RAB11FIP2") 
(PredicateNode "RAB18") 
(PredicateNode "RASGEF1A") 
(PredicateNode "RBP4") 
(PredicateNode "REEP3") 
(PredicateNode "RPS24") 
(PredicateNode "RUFY2") 
(PredicateNode "SAR1A") 
(PredicateNode "SFXN2") 
(PredicateNode "SHOC2") 
(PredicateNode "SLC35G1") 
(PredicateNode "SMC3") 
(PredicateNode "SUFU") 
(PredicateNode "SUPV3L1") 
(PredicateNode "TMEM180") 
(PredicateNode "TMEM26") 
(PredicateNode "TMEM72") 
(PredicateNode "TNKS2") 
(PredicateNode "TRIM8") 
(PredicateNode "VAX1") 
(PredicateNode "VDAC2") 
(PredicateNode "VIM") 
(PredicateNode "WDR11") 
(PredicateNode "ZMYND11") 
(PredicateNode "AASDHPPT") 
(PredicateNode "ADRBK1") 
(PredicateNode "ALDH3B1") 
(PredicateNode "ANKRD13D") 
(PredicateNode "APLNR") 
(PredicateNode "APOA1") 
(PredicateNode "ARHGAP1") 
(PredicateNode "ARHGAP20") 
(PredicateNode "ATG16L2") 
(PredicateNode "B3GNT1") 
(PredicateNode "BTBD10") 
(PredicateNode "BTBD18") 
(PredicateNode "BTG4") 
(PredicateNode "C11orf31") 
(PredicateNode "C11orf44") 
(PredicateNode "C11orf57") 
(PredicateNode "C11orf88") 
(PredicateNode "C11orf95") 
(PredicateNode "CALCB") 
(PredicateNode "CAPRIN1") 
(PredicateNode "CCDC85B") 
(PredicateNode "CCND1") 
(PredicateNode "CD151") 
(PredicateNode "CEND1") 
(PredicateNode "CHRM1") 
(PredicateNode "CLDN25") 
(PredicateNode "CRY2") 
(PredicateNode "CST6") 
(PredicateNode "CTTN") 
(PredicateNode "CYP2R1") 
(PredicateNode "DEAF1") 
(PredicateNode "DIXDC1") 
(PredicateNode "DLG2") 
(PredicateNode "EHD1") 
(PredicateNode "ELP4") 
(PredicateNode "FADD") 
(PredicateNode "FADS1") 
(PredicateNode "FADS2") 
(PredicateNode "FADS3") 
(PredicateNode "FAM118B") 
(PredicateNode "FAM76B") 
(PredicateNode "FCHSD2") 
(PredicateNode "FGF3") 
(PredicateNode "FOLR2") 
(PredicateNode "FOLR4") 
(PredicateNode "FOXR1") 
(PredicateNode "FSHB") 
(PredicateNode "GALNT18") 
(PredicateNode "H2AFX") 
(PredicateNode "HBG1") 
(PredicateNode "HPX") 
(PredicateNode "IGSF9B") 
(PredicateNode "IL18") 
(PredicateNode "IPO7") 
(PredicateNode "KCNA4") 
(PredicateNode "KCNK7") 
(PredicateNode "KCTD14") 
(PredicateNode "KLHL35") 
(PredicateNode "KRTAP5.11") 
(PredicateNode "LAYN") 
(PredicateNode "LGALS12") 
(PredicateNode "LOC100133315") 
(PredicateNode "LOC643923") 
(PredicateNode "LPXN") 
(PredicateNode "LRFN4") 
(PredicateNode "LRRC10B") 
(PredicateNode "MACROD1") 
(PredicateNode "MAP3K11") 
(PredicateNode "MAP4K2") 
(PredicateNode "MDK") 
(PredicateNode "MMP26") 
(PredicateNode "MPZL3") 
(PredicateNode "MRGPRG") 
(PredicateNode "MSANTD2") 
(PredicateNode "MTA2") 
(PredicateNode "MTRNR2L8") 
(PredicateNode "NAA40") 
(PredicateNode "NDUFC2") 
(PredicateNode "OR10A3") 
(PredicateNode "OR10G8") 
(PredicateNode "OR4D10") 
(PredicateNode "ACRBP") 
(PredicateNode "ACVR1B") 
(PredicateNode "AEBP2") 
(PredicateNode "AGAP2") 
(PredicateNode "ALDH2") 
(PredicateNode "AQP2") 
(PredicateNode "ARL6IP4") 
(PredicateNode "ARPC3") 
(PredicateNode "ATF7") 
(PredicateNode "BLOC1S1.RDH5") 
(PredicateNode "BRAP") 
(PredicateNode "C12orf57") 
(PredicateNode "C12orf74") 
(PredicateNode "C1QL4") 
(PredicateNode "C2CD5") 
(PredicateNode "CABP1") 
(PredicateNode "CCDC64") 
(PredicateNode "CD4") 
(PredicateNode "CMAS") 
(PredicateNode "CREBL2") 
(PredicateNode "CRY1") 
(PredicateNode "CSAD") 
(PredicateNode "DDIT3") 
(PredicateNode "DNAJC14") 
(PredicateNode "DTX3") 
(PredicateNode "ERP27") 
(PredicateNode "FBXO21") 
(PredicateNode "FLJ13224") 
(PredicateNode "FZD10") 
(PredicateNode "GDF11") 
(PredicateNode "GLIPR1L1") 
(PredicateNode "GPRC5A") 
(PredicateNode "GXYLT1") 
(PredicateNode "H2AFJ") 
(PredicateNode "HIGD1C") 
(PredicateNode "HIST4H4") 
(PredicateNode "HOXC13") 
(PredicateNode "HOXC8") 
(PredicateNode "HOXC9") 
(PredicateNode "HRK") 
(PredicateNode "HSD17B6") 
(PredicateNode "HSPB8") 
(PredicateNode "IFNG") 
(PredicateNode "IL22") 
(PredicateNode "KCNA1") 
(PredicateNode "KCNMB4") 
(PredicateNode "KLRC2") 
(PredicateNode "KRAS") 
(PredicateNode "KRT18") 
(PredicateNode "LACRT") 
(PredicateNode "LEMD3") 
(PredicateNode "LHX5") 
(PredicateNode "LIMA1") 
(PredicateNode "LINC01465") 
(PredicateNode "LPAR5") 
(PredicateNode "LTA4H") 
(PredicateNode "LYRM5") 
(PredicateNode "MAP3K12") 
(PredicateNode "MDM2") 
(PredicateNode "METTL7A") 
(PredicateNode "MKRN9P") 
(PredicateNode "MLEC") 
(PredicateNode "NAB2") 
(PredicateNode "NPFF") 
(PredicateNode "NTF3") 
(PredicateNode "NUP37") 
(PredicateNode "OGFOD2") 
(PredicateNode "OR6C75") 
(PredicateNode "OS9") 
(PredicateNode "OSBPL8") 
(PredicateNode "PA2G4") 
(PredicateNode "PHB2") 
(PredicateNode "PLA2G1B") 
(PredicateNode "PLEKHA5") 
(PredicateNode "PRDM4") 
(PredicateNode "PRH2") 
(PredicateNode "PRICKLE1") 
(PredicateNode "PRKAB1") 
(PredicateNode "PUS1") 
(PredicateNode "PXMP2") 
(PredicateNode "RAB3IP") 
(PredicateNode "ABHD13") 
(PredicateNode "ALOX5AP") 
(AndLink (PredicateNode "ABHD13") (NotLink (PredicateNode "EEF1DP3"))) 
(AndLink (PredicateNode "ABHD13") (PredicateNode "FRY")) 
(AndLink (PredicateNode "ABHD13") (PredicateNode "MRPS31")) 
(AndLink (PredicateNode "AKAP11") (PredicateNode "ITGBL1")) 
(AndLink (PredicateNode "ALOX5AP") (PredicateNode "C1QTNF9")) 
(AndLink (PredicateNode "ALOX5AP") (PredicateNode "HMGB1")) 
(AndLink (PredicateNode "ALOX5AP") (PredicateNode "SGCG")) 
(AndLink (PredicateNode "ALOX5AP") (PredicateNode "SLITRK1")) 
(AndLink (PredicateNode "AMER2") (PredicateNode "DCT")) 
(AndLink (PredicateNode "ARHGEF7") (PredicateNode "PCDH17")) 
(AndLink (PredicateNode "ATP11AUN") (PredicateNode "OLFM4")) 
(AndLink (PredicateNode "ATP11AUN") (PredicateNode "SLC7A1")) 
(AndLink (PredicateNode "ATP12A") (PredicateNode "DCT")) 
(AndLink (PredicateNode "ATP4B") (PredicateNode "TRPC4")) 
(AndLink (PredicateNode "B3GALTL") (PredicateNode "KBTBD6")) 
(AndLink (PredicateNode "C1QTNF9") (PredicateNode "GPR180")) 
(AndLink (PredicateNode "CARS2") (PredicateNode "EDNRB")) 
(AndLink (PredicateNode "CCDC122") (PredicateNode "PDX1")) 
(AndLink (PredicateNode "CDK8") (PredicateNode "PROZ")) 
(AndLink (PredicateNode "CHAMP1") (PredicateNode "RBM26")) 
(AndLink (PredicateNode "CLYBL") (PredicateNode "STOML3")) 
(AndLink (PredicateNode "COL4A2") (PredicateNode "ENOX1")) 
(AndLink (PredicateNode "COL4A2") (PredicateNode "SLC25A30")) 
(AndLink (PredicateNode "CSNK1A1L") (PredicateNode "TGDS")) 
(AndLink (PredicateNode "DACH1") (PredicateNode "TPP2")) 
(AndLink (PredicateNode "DCT") (PredicateNode "N4BP2L2")) 
(AndLink (PredicateNode "DCT") (PredicateNode "ZC3H13")) 
(AndLink (PredicateNode "DNAJC3") (PredicateNode "LINC00552")) 
(AndLink (PredicateNode "DNAJC3") (PredicateNode "TRIM13")) 
(AndLink (PredicateNode "DZIP1") (PredicateNode "RAB20")) 
(AndLink (PredicateNode "EBPL") (PredicateNode "SGCG")) 
(AndLink (PredicateNode "EBPL") (PredicateNode "SMAD9")) 
(AndLink (PredicateNode "ENOX1") (NotLink (PredicateNode "INTS6"))) 
(AndLink (PredicateNode "ENOX1") (PredicateNode "MBNL2")) 
(AndLink (PredicateNode "EXOSC8") (PredicateNode "GRK1")) 
(AndLink (PredicateNode "EXOSC8") (PredicateNode "MBNL2")) 
(AndLink (PredicateNode "EXOSC8") (PredicateNode "PABPC3")) 
(AndLink (PredicateNode "FAM124A") (PredicateNode "UFM1")) 
(AndLink (PredicateNode "FOXO1") (PredicateNode "TPTE2P1")) 
(AndLink (PredicateNode "FREM2") (PredicateNode "ZIC2")) 
(AndLink (PredicateNode "GJA3") (PredicateNode "SLC25A30")) 
(AndLink (PredicateNode "GJB6") (PredicateNode "MTRF1")) 
(AndLink (PredicateNode "GJB6") (PredicateNode "RCBTB2")) 
(AndLink (PredicateNode "GPR180") (PredicateNode "POU4F1")) 
(AndLink (PredicateNode "GPR180") (PredicateNode "SHISA2")) 
(AndLink (PredicateNode "GSX1") (PredicateNode "RPL21")) 
(AndLink (PredicateNode "GSX1") (PredicateNode "SERPINE3")) 
(AndLink (PredicateNode "HS6ST3") (PredicateNode "RASL11A")) 
(AndLink (PredicateNode "HSPH1") (PredicateNode "TEX30")) 
(AndLink (PredicateNode "HTR2A") (PredicateNode "RCBTB2")) 
(AndLink (PredicateNode "IRG1") (PredicateNode "POSTN")) 
(AndLink (PredicateNode "IRG1") (PredicateNode "TGDS")) 
(AndLink (PredicateNode "KBTBD6") (PredicateNode "KL")) 
(AndLink (PredicateNode "KBTBD6") (PredicateNode "MIPEP")) 
(PredicateNode "DCT") 
(PredicateNode "DNAJC3") 
(PredicateNode "EBPL") 
(PredicateNode "ENOX1") 
(PredicateNode "FBXL3") 
(PredicateNode "FOXO1") 
(PredicateNode "GPR180") 
(PredicateNode "GSX1") 
(PredicateNode "KBTBD6") 
(PredicateNode "KBTBD7") 
(PredicateNode "KCTD12") 
(PredicateNode "KLF12") 
(PredicateNode "MBNL2") 
(PredicateNode "NAA16") 
(PredicateNode "OXGR1") 
(PredicateNode "PDX1") 
(PredicateNode "RAB20") 
(PredicateNode "RASL11A") 
(PredicateNode "RB1") 
(PredicateNode "RCBTB2") 
(PredicateNode "RGCC") 
(PredicateNode "RPL21") 
(PredicateNode "SLC25A30") 
(PredicateNode "SLC46A3") 
(PredicateNode "SLC7A1") 
(PredicateNode "SLITRK5") 
(PredicateNode "STOML3") 
(PredicateNode "TEX30") 
(PredicateNode "TGDS") 
(PredicateNode "TNFSF13B") 
(PredicateNode "TPP2") 
(PredicateNode "ZIC2") 
(PredicateNode "ACTR10") 
(AndLink (PredicateNode "ABCD4") (PredicateNode "RCOR1")) 
(AndLink (PredicateNode "ACTR10") (NotLink (PredicateNode "ZNF410"))) 
(AndLink (PredicateNode "ADAM21") (PredicateNode "COX8C")) 
(AndLink (PredicateNode "ADCK1") (PredicateNode "AMN")) 
(AndLink (PredicateNode "ADCK1") (PredicateNode "GPHN")) 
(AndLink (PredicateNode "ADCK1") (PredicateNode "TGFB3")) 
(AndLink (PredicateNode "AJUBA") (PredicateNode "NUDT14")) 
(AndLink (PredicateNode "AJUBA") (PredicateNode "TXNDC16")) 
(AndLink (PredicateNode "ALKBH1") (PredicateNode "PRKD1")) 
(AndLink (PredicateNode "AMN") (PredicateNode "METTL17")) 
(AndLink (PredicateNode "ANKRD9") (PredicateNode "FITM1")) 
(AndLink (PredicateNode "BATF") (PredicateNode "CHD8")) 
(AndLink (PredicateNode "BAZ1A") (PredicateNode "CYP46A1")) 
(AndLink (PredicateNode "BDKRB1") (PredicateNode "ELMSAN1")) 
(PredicateNode "ATL1") 
(PredicateNode "BATF") 
(PredicateNode "BDKRB1") 
(PredicateNode "BTBD6") 
(PredicateNode "CCNB1IP1") 
(PredicateNode "CDC42BPB") 
(PredicateNode "CHMP4A") 
(PredicateNode "CHURC1.FNTB") 
(PredicateNode "CIPC") 
(PredicateNode "COX8C") 
(PredicateNode "CRIP2") 
(PredicateNode "CYP46A1") 
(PredicateNode "EFCAB11") 
(PredicateNode "EGLN3") 
(PredicateNode "EIF5") 
(PredicateNode "ERO1L") 
(PredicateNode "FBXO33") 
(PredicateNode "GPR33") 
(PredicateNode "GTF2A1") 
(PredicateNode "HAUS4") 
(PredicateNode "IRF9") 
(PredicateNode "JPH4") 
(PredicateNode "KLHDC1") 
(PredicateNode "KLHDC2") 
(PredicateNode "LTB4R") 
(PredicateNode "LTB4R2") 
(PredicateNode "MAX") 
(PredicateNode "NAA30") 
(PredicateNode "NFKBIA") 
(PredicateNode "NKX2.1") 
(PredicateNode "NRL") 
(PredicateNode "NUBPL") 
(PredicateNode "OR4N5") 
(PredicateNode "POMT2") 
(PredicateNode "PSMC1") 
(PredicateNode "PSME1") 
(PredicateNode "PTGER2") 
(PredicateNode "RAB2B") 
(PredicateNode "RCOR1") 
(PredicateNode "RNASE1") 
(PredicateNode "RNASE2") 
(PredicateNode "RPL10L") 
(PredicateNode "SGPP1") 
(PredicateNode "SLC22A17") 
(PredicateNode "SLC35F4") 
(PredicateNode "SSTR1") 
(PredicateNode "TEX22") 
(PredicateNode "TGFB3") 
(PredicateNode "TMED10") 
(PredicateNode "TMEM229B") 
(PredicateNode "TMEM55B") 
(PredicateNode "TRAPPC6B") 
(PredicateNode "TTC8") 
(PredicateNode "VIPAS39") 
(PredicateNode "VTI1B") 
(PredicateNode "WDR89") 
(PredicateNode "ZC3H14") 
(PredicateNode "ZFP36L1") 
(PredicateNode "ABHD17C") 
(AndLink (PredicateNode "AAGAB") (PredicateNode "CASC4")) 
(AndLink (PredicateNode "ABHD17C") (PredicateNode "LOC645752")) 
(AndLink (PredicateNode "ABHD17C") (PredicateNode "NR2E3")) 
(AndLink (PredicateNode "ABHD17C") (PredicateNode "RYR3")) 
(AndLink (PredicateNode "ABHD17C") (PredicateNode "TYRO3")) 
(AndLink (PredicateNode "ADAMTS7") (PredicateNode "CKMT1A")) 
(AndLink (PredicateNode "ADAMTS7") (PredicateNode "PDCD7")) 
(AndLink (PredicateNode "ALDH1A2") (PredicateNode "AP3B2")) 
(AndLink (PredicateNode "AP3B2") (PredicateNode "NR2F2")) 
(AndLink (PredicateNode "AP3B2") (NotLink (PredicateNode "TUBGCP4"))) 
(AndLink (PredicateNode "AP4E1") (PredicateNode "PSMA4")) 
(AndLink (PredicateNode "AQR") (NotLink (PredicateNode "GOLGA6A"))) 
(AndLink (PredicateNode "ARID3B") (PredicateNode "SMAD3")) 
(AndLink (PredicateNode "ARIH1") (PredicateNode "MCTP2")) 
(AndLink (PredicateNode "ARIH1") (PredicateNode "MNS1")) 
(AndLink (PredicateNode "ARIH1") (PredicateNode "TTC23")) 
(AndLink (PredicateNode "ATP8B4") (PredicateNode "CIB1")) 
(PredicateNode "AP3B2") 
(PredicateNode "AQR") 
(PredicateNode "ARIH1") 
(PredicateNode "BLOC1S6") 
(PredicateNode "C15orf38.AP3S2") 
(PredicateNode "CALML4") 
(PredicateNode "CASC4") 
(PredicateNode "CHRM5") 
(PredicateNode "CHST14") 
(PredicateNode "CIB1") 
(PredicateNode "CIB2") 
(PredicateNode "CKMT1A") 
(PredicateNode "CORO2B") 
(PredicateNode "CPLX3") 
(PredicateNode "CRABP1") 
(PredicateNode "CXADRP2") 
(PredicateNode "DDX11L9") 
(PredicateNode "DENND4A") 
(PredicateNode "DKFZP434L187") 
(PredicateNode "DPH6") 
(PredicateNode "EDC3") 
(PredicateNode "EMC7") 
(PredicateNode "FAM219B") 
(PredicateNode "FES") 
(PredicateNode "FGF7") 
(PredicateNode "FLJ10038") 
(PredicateNode "FRMD5") 
(PredicateNode "GJD2") 
(PredicateNode "GOLGA6L1") 
(NotLink (PredicateNode "GOLGA6L10")) 
(PredicateNode "GOLGA6L7P") 
(PredicateNode "HDGFRP3") 
(PredicateNode "IMP3") 
(PredicateNode "ITPKA") 
(PredicateNode "LEO1") 
(PredicateNode "MEIS2") 
(PredicateNode "MESDC1") 
(PredicateNode "MKRN3") 
(PredicateNode "NR2F2") 
(PredicateNode "OIP5") 
(PredicateNode "OR4F4") 
(PredicateNode "OR4N3P") 
(PredicateNode "PARP16") 
(PredicateNode "PDCD7") 
(PredicateNode "PGBD4") 
(PredicateNode "PIAS1") 
(PredicateNode "PPIP5K1") 
(PredicateNode "PSMA4") 
(PredicateNode "PTPN9") 
(PredicateNode "RHOV") 
(PredicateNode "SIN3A") 
(PredicateNode "SLC24A5") 
(PredicateNode "SNX22") 
(PredicateNode "ST8SIA2") 
(PredicateNode "SV2B") 
(PredicateNode "TMEM62") 
(PredicateNode "TMEM87A") 
(PredicateNode "TMOD2") 
(PredicateNode "TMOD3") 
(PredicateNode "TPM1") 
(PredicateNode "USP3") 
(PredicateNode "USP50") 
(PredicateNode "VIMP") 
(PredicateNode "ZFAND6") 
(PredicateNode "ALDOA") 
(PredicateNode "ARHGDIG") 
(PredicateNode "ATP2A1") 
(PredicateNode "B3GNT9") 
(PredicateNode "C16orf54") 
(PredicateNode "C16orf93") 
(PredicateNode "CBFB") 
(PredicateNode "CBLN1") 
(PredicateNode "CCDC101") 
(PredicateNode "CDIPT") 
(PredicateNode "CDR2") 
(PredicateNode "CREBBP") 
(PredicateNode "CSNK2A2") 
(PredicateNode "CTCF") 
(PredicateNode "CYB5B") 
(PredicateNode "DDX19B") 
(PredicateNode "E2F4") 
(PredicateNode "ESRP2") 
(PredicateNode "FAM173A") 
(PredicateNode "FAM192A") 
(PredicateNode "FTO") 
(PredicateNode "GDE1") 
(PredicateNode "GLYR1") 
(PredicateNode "HBA1") 
(PredicateNode "HBM") 
(PredicateNode "HBZ") 
(PredicateNode "HEATR3") 
(PredicateNode "HMOX2") 
(PredicateNode "HSF4") 
(PredicateNode "IL32") 
(PredicateNode "INO80E") 
(PredicateNode "KCTD13") 
(PredicateNode "KIFC3") 
(PredicateNode "LOC100862671") 
(PredicateNode "LOC613037") 
(PredicateNode "LOC613038") 
(PredicateNode "MAZ") 
(PredicateNode "MPV17L") 
(PredicateNode "MT1F") 
(PredicateNode "MT1G") 
(PredicateNode "NAE1") 
(PredicateNode "NDUFB10") 
(PredicateNode "NPIPA1") 
(PredicateNode "NPIPB5") 
(PredicateNode "NTN3") 
(PredicateNode "NUBP2") 
(PredicateNode "ORAI3") 
(PredicateNode "PARN") 
(PredicateNode "PHKG2") 
(PredicateNode "PLLP") 
(PredicateNode "PRKCB") 
(PredicateNode "PRM2") 
(PredicateNode "PRMT7") 
(PredicateNode "PRSS30P") 
(PredicateNode "PSKH1") 
(PredicateNode "PYCARDOS") 
(PredicateNode "PYDC1") 
(PredicateNode "RANBP10") 
(PredicateNode "RBFOX1") 
(PredicateNode "ROGDI") 
(PredicateNode "RRAD") 
(PredicateNode "SBK1") 
(PredicateNode "SEC14L5") 
(PredicateNode "SEPT12") 
(PredicateNode "SIAH1") 
(PredicateNode "SLC6A10P") 
(PredicateNode "SMG1P3") 
(PredicateNode "SNRNP25") 
(PredicateNode "SNX20") 
(PredicateNode "STX4") 
(PredicateNode "TERF2") 
(PredicateNode "TK2") 
(PredicateNode "ACACA") 
(PredicateNode "ACSF2") 
(PredicateNode "ALYREF") 
(PredicateNode "ANKRD13B") 
(PredicateNode "AOC4P") 
(PredicateNode "APPBP2") 
(PredicateNode "ASGR1") 
(PredicateNode "ATP5G1") 
(PredicateNode "BHLHA9") 
(PredicateNode "C17orf105") 
(PredicateNode "C17orf64") 
(PredicateNode "C17orf75") 
(PredicateNode "C17orf85") 
(PredicateNode "C1QL1") 
(PredicateNode "CACNG4") 
(PredicateNode "CCDC103") 
(PredicateNode "CCL3") 
(PredicateNode "CCL3L1") 
(PredicateNode "CD79B") 
(PredicateNode "CDC27") 
(PredicateNode "CDC42EP4") 
(PredicateNode "CDK5R1") 
(PredicateNode "CHMP6") 
(PredicateNode "CNP") 
(PredicateNode "CPSF4L") 
(PredicateNode "CRK") 
(PredicateNode "CYGB") 
(PredicateNode "DGKE") 
(PredicateNode "DHX8") 
(PredicateNode "DLG4") 
(PredicateNode "DUSP14") 
(PredicateNode "FAM106A") 
(PredicateNode "FAM222B") 
(PredicateNode "FAM64A") 
(PredicateNode "FLJ45513") 
(PredicateNode "FXR2") 
(PredicateNode "G6PC") 
(PredicateNode "GALK1") 
(PredicateNode "GAST") 
(PredicateNode "GDPD1") 
(PredicateNode "GIT1") 
(PredicateNode "GNA13") 
(PredicateNode "GPS1") 
(PredicateNode "GRB2") 
(PredicateNode "HCRT") 
(PredicateNode "HES7") 
(PredicateNode "HID1") 
(PredicateNode "HOXB13") 
(PredicateNode "HOXB8") 
(PredicateNode "HOXB9") 
(PredicateNode "IGFBP4") 
(PredicateNode "JMJD6") 
(PredicateNode "KAT2A") 
(PredicateNode "KAT7") 
(PredicateNode "KCNH4") 
(PredicateNode "KCNJ16") 
(PredicateNode "KRBA2") 
(PredicateNode "KRT17") 
(PredicateNode "KRT222") 
(PredicateNode "KRT9") 
(PredicateNode "KRTAP4.4") 
(PredicateNode "LINC00483") 
(PredicateNode "LRRC37A3") 
(PredicateNode "LRRC46") 
(PredicateNode "MAFG") 
(PredicateNode "MAP2K3") 
(PredicateNode "MED1") 
(PredicateNode "MED11") 
(PredicateNode "MED24") 
(PredicateNode "MFSD11") 
(PredicateNode "MIEN1") 
(PredicateNode "MMD") 
(PredicateNode "MSL1") 
(PredicateNode "NAGS") 
(PredicateNode "NEK8") 
(PredicateNode "NEUROD2") 
(PredicateNode "NME1.NME2") 
(PredicateNode "NOL11") 
(PredicateNode "NPLOC4") 
(PredicateNode "ABHD3") 
(AndLink (PredicateNode "ABHD3") (PredicateNode "FAM210A")) 
(AndLink (PredicateNode "ABHD3") (PredicateNode "GREB1L")) 
(AndLink (PredicateNode "ABHD3") (PredicateNode "TRAPPC8")) 
(AndLink (PredicateNode "ADCYAP1") (PredicateNode "SMAD4")) 
(AndLink (PredicateNode "ADNP2") (PredicateNode "PQLC1")) 
(AndLink (PredicateNode "ADNP2") (PredicateNode "SERPINB4")) 
(AndLink (PredicateNode "ANKRD12") (PredicateNode "SLMO1")) 
(AndLink (PredicateNode "ANKRD29") (PredicateNode "GAREM")) 
(AndLink (PredicateNode "ATP5A1") (PredicateNode "INO80C")) 
(AndLink (PredicateNode "ATP5A1") (PredicateNode "TIMM21")) 
(AndLink (PredicateNode "BCL2") (PredicateNode "HRH4")) 
(AndLink (PredicateNode "BCL2") (PredicateNode "STARD6")) 
(AndLink (PredicateNode "BCL2") (PredicateNode "TTC39C")) 
(AndLink (PredicateNode "C18orf21") (PredicateNode "SPIRE1")) 
(AndLink (PredicateNode "C18orf42") (PredicateNode "RNF165")) 
(AndLink (PredicateNode "C18orf54") (PredicateNode "CCBE1")) 
(AndLink (PredicateNode "C18orf54") (PredicateNode "ZNF532")) 
(AndLink (PredicateNode "CCBE1") (PredicateNode "CHST9")) 
(AndLink (PredicateNode "CDH20") (PredicateNode "TPGS2")) 
(AndLink (PredicateNode "CELF4") (PredicateNode "ZNF516")) 
(AndLink (PredicateNode "CNDP2") (PredicateNode "TCEB3CL2")) 
(AndLink (PredicateNode "CTIF") (PredicateNode "TUBB6")) 
(AndLink (PredicateNode "CTIF") (PredicateNode "ZNF397")) 
(AndLink (PredicateNode "DSEL") (PredicateNode "MAPRE2")) 
(AndLink (PredicateNode "DSEL") (PredicateNode "SLMO1")) 
(AndLink (PredicateNode "ELP2") (PredicateNode "SMAD4")) 
(AndLink (PredicateNode "FAM210A") (PredicateNode "MAPRE2")) 
(AndLink (PredicateNode "FBXO15") (PredicateNode "NOL4")) 
(AndLink (PredicateNode "FBXO15") (PredicateNode "TYMS")) 
(AndLink (PredicateNode "GALNT1") (PredicateNode "TCEB3CL2")) 
(AndLink (PredicateNode "GATA6") (PredicateNode "RAX")) 
(AndLink (PredicateNode "GATA6") (PredicateNode "SALL3")) 
(AndLink (PredicateNode "GATA6") (PredicateNode "ZNF236")) 
(AndLink (PredicateNode "HAUS1") (PredicateNode "TWSG1")) 
(AndLink (PredicateNode "INO80C") (PredicateNode "ZNF396")) 
(AndLink (PredicateNode "KCNG2") (PredicateNode "SLMO1")) 
(AndLink (PredicateNode "KCTD1") (PredicateNode "ZBTB7C")) 
(AndLink (PredicateNode "KIAA1328") (PredicateNode "RALBP1")) 
(AndLink (PredicateNode "KIAA1468") (PredicateNode "MEX3C")) 
(AndLink (PredicateNode "LINC00907") (PredicateNode "RBBP8")) 
(AndLink (PredicateNode "LIPG") (PredicateNode "MEX3C")) 
(AndLink (PredicateNode "LRRC30") (NotLink (PredicateNode "ANKRD20A5P"))) 
(AndLink (PredicateNode "LRRC30") (PredicateNode "ZNF271")) 
(AndLink (PredicateNode "MAPRE2") (PredicateNode "SERPINB2")) 
(AndLink (PredicateNode "MAPRE2") (PredicateNode "SERPINB8")) 
(AndLink (PredicateNode "MBP") (PredicateNode "TPGS2")) 
(AndLink (PredicateNode "MC5R") (PredicateNode "ROCK1")) 
(AndLink (PredicateNode "MIB1") (NotLink (PredicateNode "ANKRD20A5P"))) 
(AndLink (PredicateNode "MIB1") (PredicateNode "NOL4")) 
(AndLink (PredicateNode "MRO") (PredicateNode "PARD6G")) 
(AndLink (PredicateNode "NOL4") (NotLink (PredicateNode "LDLRAD4"))) 
(AndLink (PredicateNode "NOL4") (PredicateNode "PTPRM")) 
(AndLink (PredicateNode "OSBPL1A") (PredicateNode "RNF165")) 
(AndLink (PredicateNode "POLI") (PredicateNode "ZNF396")) 
(AndLink (PredicateNode "PQLC1") (PredicateNode "TYMSOS")) 
(AndLink (PredicateNode "PTPN2") (PredicateNode "SPIRE1")) 
(AndLink (PredicateNode "SERPINB4") (PredicateNode "TWSG1")) 
(AndLink (PredicateNode "SERPINB5") (PredicateNode "TUBB6")) 
(AndLink (PredicateNode "SETBP1") (PredicateNode "TCEB3C")) 
(AndLink (PredicateNode "SLC39A6") (PredicateNode "TCEB3CL2")) 
(AndLink (PredicateNode "SLMO1") (PredicateNode "ST8SIA3")) 
(AndLink (PredicateNode "SLMO1") (PredicateNode "TMEM200C")) 
(PredicateNode "ANKRD29") 
(PredicateNode "CELF4") 
(PredicateNode "GATA6") 
(PredicateNode "KDSR") 
(PredicateNode "LRRC30") 
(PredicateNode "MAPRE2") 
(PredicateNode "NOL4") 
(PredicateNode "ONECUT2") 
(PredicateNode "PARD6G") 
(PredicateNode "PSMA8") 
(PredicateNode "SLMO1") 
(PredicateNode "SMAD4") 
(PredicateNode "SNRPD1") 
(PredicateNode "SPIRE1") 
(PredicateNode "SYT4") 
(PredicateNode "TCEB3C") 
(PredicateNode "TCEB3CL2") 
(PredicateNode "TUBB6") 
(PredicateNode "TYMS") 
(PredicateNode "WDR7") 
(PredicateNode "ZNF396") 
(PredicateNode "ZNF397") 
(PredicateNode "ADAMTSL5") 
(PredicateNode "AES") 
(PredicateNode "ALKBH6") 
(PredicateNode "ARMC6") 
(PredicateNode "BAX") 
(PredicateNode "BBC3") 
(PredicateNode "BCL3") 
(PredicateNode "C19orf18") 
(PredicateNode "C19orf44") 
(PredicateNode "C19orf47") 
(PredicateNode "C19orf52") 
(PredicateNode "C19orf66") 
(PredicateNode "C5AR2") 
(PredicateNode "CCDC97") 
(PredicateNode "CDC37") 
(PredicateNode "CEACAM3") 
(PredicateNode "CEBPA") 
(PredicateNode "CELF5") 
(PredicateNode "CHST8") 
(PredicateNode "CIC") 
(PredicateNode "CIRBP") 
(PredicateNode "CLDND2") 
(PredicateNode "CLIP3") 
(PredicateNode "CNFN") 
(PredicateNode "COX6B2") 
(PredicateNode "CRX") 
(PredicateNode "DACT3") 
(PredicateNode "DAPK3") 
(PredicateNode "DDA1") 
(PredicateNode "DHPS") 
(PredicateNode "DIRAS1") 
(PredicateNode "DMRTC2") 
(PredicateNode "DNAJB1") 
(PredicateNode "DNASE2") 
(PredicateNode "DNM2") 
(PredicateNode "DPF1") 
(PredicateNode "DPP9.AS1") 
(PredicateNode "DPY19L3") 
(PredicateNode "DYRK1B") 
(PredicateNode "EFNA2") 
(PredicateNode "EHD2") 
(PredicateNode "ELAVL3") 
(PredicateNode "EPS15L1") 
(PredicateNode "FBXL12") 
(PredicateNode "FEM1A") 
(PredicateNode "FKBP8") 
(PredicateNode "FXYD1") 
(PredicateNode "FZR1") 
(PredicateNode "GATAD2A") 
(PredicateNode "GDF1") 
(PredicateNode "GIPC3") 
(PredicateNode "GPR4") 
(PredicateNode "GSK3A") 
(PredicateNode "HAPLN4") 
(PredicateNode "HCST") 
(PredicateNode "HNRNPM") 
(PredicateNode "HSD11B1L") 
(PredicateNode "ICAM4") 
(PredicateNode "IGFL2") 
(PredicateNode "IRF2BP1") 
(PredicateNode "ISYNA1") 
(PredicateNode "JAK3") 
(PredicateNode "JUNB") 
(PredicateNode "KCNN4") 
(PredicateNode "KCTD15") 
(PredicateNode "KLC3") 
(PredicateNode "KPTN") 
(PredicateNode "KRTDAP") 
(PredicateNode "LGALS4") 
(PredicateNode "LILRA5") 
(PredicateNode "LOC100128398") 
(PredicateNode "LOC284379") 
(PredicateNode "LPAR2") 
(PredicateNode "LRFN1") 
(PredicateNode "MAP4K1") 
(PredicateNode "MAST1") 
(PredicateNode "MAU2") 
(PredicateNode "MEF2BNB.MEF2B") 
(PredicateNode "NDUFA13") 
(PredicateNode "NFIX") 
(PredicateNode "NOVA2") 
(PredicateNode "ABCD3") 
(PredicateNode "ACTA1") 
(PredicateNode "ADORA1") 
(PredicateNode "ADPRHL2") 
(PredicateNode "AGO3") 
(PredicateNode "AGO4") 
(PredicateNode "AGTRAP") 
(PredicateNode "AIM2") 
(PredicateNode "ALDH9A1") 
(PredicateNode "ALX3") 
(PredicateNode "ANGPTL3") 
(PredicateNode "ANKRD13C") 
(PredicateNode "ANKRD34A") 
(PredicateNode "APITD1") 
(PredicateNode "APOA2") 
(PredicateNode "ASAP3") 
(PredicateNode "B3GALNT2") 
(PredicateNode "B3GALT6") 
(PredicateNode "BGLAP") 
(PredicateNode "BSND") 
(PredicateNode "C1orf122") 
(PredicateNode "C1orf146") 
(PredicateNode "C1orf186") 
(PredicateNode "C1orf192") 
(PredicateNode "C1orf198") 
(PredicateNode "C1orf226") 
(PredicateNode "C1orf234") 
(PredicateNode "CAMK2N1") 
(PredicateNode "CCDC163P") 
(PredicateNode "CCDC23") 
(PredicateNode "CD160") 
(PredicateNode "CD247") 
(PredicateNode "CDC7") 
(PredicateNode "CFHR1") 
(PredicateNode "CKS1B") 
(PredicateNode "CRB1") 
(PredicateNode "CTRC") 
(PredicateNode "CYB5R1") 
(PredicateNode "DDAH1") 
(PredicateNode "DEDD") 
(PredicateNode "DFFA") 
(PredicateNode "DMBX1") 
(PredicateNode "DNM3") 
(PredicateNode "DPH5") 
(PredicateNode "DYRK3") 
(PredicateNode "EFCAB14") 
(PredicateNode "EMBP1") 
(PredicateNode "ENAH") 
(PredicateNode "EXTL2") 
(PredicateNode "EYA3") 
(PredicateNode "FAM159A") 
(PredicateNode "FAM189B") 
(PredicateNode "FAM43B") 
(PredicateNode "FAM69A") 
(PredicateNode "FAM72A") 
(PredicateNode "FAM73A") 
(PredicateNode "FBXO28") 
(PredicateNode "FCGR1A") 
(PredicateNode "FHL3") 
(PredicateNode "FMO1") 
(PredicateNode "FMO9P") 
(PredicateNode "FUBP1") 
(PredicateNode "GALE") 
(PredicateNode "GJA8") 
(PredicateNode "GJC2") 
(PredicateNode "GPATCH3") 
(PredicateNode "GPR3") 
(PredicateNode "GPR61") 
(PredicateNode "GPR89A") 
(PredicateNode "GPX7") 
(PredicateNode "GREM2") 
(PredicateNode "H3F3A") 
(PredicateNode "HAPLN2") 
(PredicateNode "HFE2") 
(PredicateNode "AAR2") 
(PredicateNode "ACTL10") 
(AndLink (PredicateNode "ABHD12") (PredicateNode "OCSTAMP")) 
(AndLink (PredicateNode "ABHD16B") (PredicateNode "CDH26")) 
(AndLink (PredicateNode "ACOT8") (PredicateNode "SUN5")) 
(AndLink (PredicateNode "ADRA1D") (PredicateNode "DEFB132")) 
(AndLink (PredicateNode "ADRA1D") (PredicateNode "PTGIS")) 
(AndLink (PredicateNode "AHCY") (PredicateNode "CD40")) 
(AndLink (PredicateNode "ANGPT4") (PredicateNode "SEMG2")) 
(AndLink (PredicateNode "AP5S1") (PredicateNode "FLJ16779")) 
(AndLink (PredicateNode "AP5S1") (PredicateNode "PAK7")) 
(AndLink (PredicateNode "AP5S1") (PredicateNode "SLC17A9")) 
(AndLink (PredicateNode "AP5S1") (PredicateNode "ZNF133")) 
(PredicateNode "AP5S1") 
(PredicateNode "AVP") 
(PredicateNode "BHLHE23") 
(PredicateNode "BPIFA2") 
(PredicateNode "C20orf144") 
(PredicateNode "C20orf203") 
(PredicateNode "C20orf27") 
(PredicateNode "CCM2L") 
(PredicateNode "CEBPB") 
(PredicateNode "COMMD7") 
(PredicateNode "CST4") 
(PredicateNode "CST7") 
(PredicateNode "DBNDD2") 
(PredicateNode "DEFB124") 
(PredicateNode "DEFB126") 
(PredicateNode "EBF4") 
(PredicateNode "ELMO2") 
(PredicateNode "EPPIN") 
(PredicateNode "EPPIN.WFDC6") 
(PredicateNode "FAM217B") 
(PredicateNode "FOXA2") 
(PredicateNode "GFRA4") 
(PredicateNode "HMGB3P1") 
(PredicateNode "IDH3B") 
(PredicateNode "INSM1") 
(PredicateNode "LOC100131496") 
(PredicateNode "LSM14B") 
(PredicateNode "LZTS3") 
(PredicateNode "MAFB") 
(PredicateNode "MAP1LC3A") 
(PredicateNode "MRGBP") 
(PredicateNode "MRPS26") 
(PredicateNode "NAPB") 
(PredicateNode "NDUFAF5") 
(PredicateNode "OXT") 
(PredicateNode "PPDPF") 
(PredicateNode "PRPF6") 
(PredicateNode "PTGIS") 
(PredicateNode "RALGAPB") 
(PredicateNode "RBM12") 
(PredicateNode "RBM38") 
(PredicateNode "SCAND1") 
(PredicateNode "SCRT2") 
(PredicateNode "SLC32A1") 
(PredicateNode "SMOX") 
(PredicateNode "SNRPB") 
(PredicateNode "SPAG4") 
(PredicateNode "SPEF1") 
(PredicateNode "SRC") 
(PredicateNode "SS18L1") 
(PredicateNode "STAU1") 
(PredicateNode "SYNDIG1") 
(PredicateNode "TGIF2") 
(PredicateNode "TMEM74B") 
(PredicateNode "TOMM34") 
(PredicateNode "TOP1") 
(PredicateNode "TP53INP2") 
(PredicateNode "TRPC4AP") 
(PredicateNode "TTLL9") 
(PredicateNode "UCKL1") 
(PredicateNode "WFDC13") 
(PredicateNode "XRN2") 
(PredicateNode "YWHAB") 
(PredicateNode "ZNF663P") 
(AndLink (PredicateNode "ATP5J") (PredicateNode "IFNGR2")) 
(AndLink (PredicateNode "BTG3") (PredicateNode "CLDN8")) 
(AndLink (PredicateNode "BTG3") (PredicateNode "TRPM2")) 
(AndLink (PredicateNode "C21orf33") (PredicateNode "CLDN14")) 
(AndLink (PredicateNode "C21orf67") (PredicateNode "DONSON")) 
(AndLink (PredicateNode "C21orf67") (PredicateNode "SETD4")) 
(AndLink (PredicateNode "CBS") (PredicateNode "CLDN17")) 
(AndLink (PredicateNode "CBS") (PredicateNode "RRP1B")) 
(AndLink (PredicateNode "CLDN14") (PredicateNode "KRTAP19.4")) 
(AndLink (PredicateNode "CLDN14") (PredicateNode "MIS18A")) 
(AndLink (PredicateNode "CLIC6") (PredicateNode "KRTAP6.2")) 
(AndLink (PredicateNode "COL18A1") (PredicateNode "CYYR1")) 
(AndLink (PredicateNode "DYRK1A") (PredicateNode "FAM207A")) 
(AndLink (PredicateNode "ERG") (PredicateNode "N6AMT1")) 
(AndLink (PredicateNode "ERG") (PredicateNode "SETD4")) 
(AndLink (PredicateNode "EVA1C") (PredicateNode "POTED")) 
(AndLink (PredicateNode "FAM3B") (PredicateNode "KRTAP6.2")) 
(AndLink (PredicateNode "GRIK1") (PredicateNode "HSF2BP")) 
(AndLink (PredicateNode "HLCS") (PredicateNode "URB1")) 
(AndLink (PredicateNode "HSF2BP") (PredicateNode "PFKL")) 
(AndLink (PredicateNode "ITSN1") (PredicateNode "PLAC4")) 
(AndLink (PredicateNode "KRTAP10.12") (PredicateNode "KRTAP21.1")) 
(AndLink (PredicateNode "KRTAP12.3") (PredicateNode "SMIM11")) 
(AndLink (PredicateNode "KRTAP19.6") (PredicateNode "MAP3K7CL")) 
(AndLink (PredicateNode "KRTAP19.8") (PredicateNode "MAP3K7CL")) 
(AndLink (PredicateNode "MIS18A") (PredicateNode "SH3BGR")) 
(AndLink (PredicateNode "MRAP") (PredicateNode "RSPH1")) 
(AndLink (PredicateNode "OLIG2") (PredicateNode "SIM2")) 
(AndLink (PredicateNode "SETD4") (PredicateNode "UBE2G2")) 
(AndLink (PredicateNode "SETD4") (PredicateNode "YBEY")) 
(AndLink (PredicateNode "UBE2G2") (NotLink (PredicateNode "APP"))) 
(PredicateNode "ATP5J") 
(PredicateNode "BTG3") 
(PredicateNode "CBS") 
(PredicateNode "CLDN14") 
(PredicateNode "CYYR1") 
(PredicateNode "DYRK1A") 
(PredicateNode "ERG") 
(PredicateNode "HSF2BP") 
(PredicateNode "KRTAP21.1") 
(PredicateNode "KRTAP22.2") 
(PredicateNode "KRTAP6.2") 
(PredicateNode "MAP3K7CL") 
(PredicateNode "MIS18A") 
(PredicateNode "MRAP") 
(PredicateNode "MX2") 
(PredicateNode "OLIG2") 
(OrLink (NotLink (PredicateNode "ADARB1")) (PredicateNode "CLDN14")) 
(OrLink (NotLink (PredicateNode "ADARB1")) (PredicateNode "HSF2BP")) 
(OrLink (PredicateNode "ATP5J") (NotLink (PredicateNode "LOC388813"))) 
(OrLink (PredicateNode "ATP5J") (NotLink (PredicateNode "RIPK4"))) 
(OrLink (PredicateNode "ATP5J") (NotLink (PredicateNode "UMODL1"))) 
(OrLink (NotLink (PredicateNode "C21orf88")) (PredicateNode "UBE2G2")) 
(OrLink (PredicateNode "CLDN14") (NotLink (PredicateNode "KRTAP10.6"))) 
(OrLink (PredicateNode "CLDN14") (NotLink (PredicateNode "SLC5A3"))) 
(OrLink (PredicateNode "DYRK1A") (PredicateNode "KRTAP21.1")) 
(OrLink (PredicateNode "HSF2BP") (NotLink (PredicateNode "RIPK4"))) 
(OrLink (NotLink (PredicateNode "PRDM15")) (PredicateNode "SMIM11")) 
(OrLink (NotLink (PredicateNode "RIPK4")) (PredicateNode "SMIM11")) 
(PredicateNode "SMIM11") 
(PredicateNode "UBE2G2") 
(PredicateNode "ADORA2A") 
(PredicateNode "ADRBK2") 
(AndLink (PredicateNode "A4GALT") (PredicateNode "CHEK2")) 
(AndLink (PredicateNode "ACO2") (PredicateNode "MAPK12")) 
(AndLink (PredicateNode "ADRBK2") (PredicateNode "AP1B1")) 
(AndLink (PredicateNode "AIFM3") (PredicateNode "SLC25A17")) 
(AndLink (PredicateNode "AIFM3") (PredicateNode "TMEM184B")) 
(AndLink (PredicateNode "ALG12") (PredicateNode "GGT1")) 
(AndLink (PredicateNode "ANKRD54") (PredicateNode "GGA1")) 
(AndLink (PredicateNode "APOBEC3C") (PredicateNode "ELFN2")) 
(AndLink (PredicateNode "APOBEC3C") (PredicateNode "KCTD17")) 
(AndLink (PredicateNode "APOBEC3D") (PredicateNode "NCAPH2")) 
(AndLink (PredicateNode "APOBEC3G") (PredicateNode "CRYBB1")) 
(AndLink (PredicateNode "APOBEC3G") (PredicateNode "PI4KA")) 
(AndLink (PredicateNode "ARFGAP3") (PredicateNode "RANBP1")) 
(AndLink (PredicateNode "ARSA") (PredicateNode "OSM")) 
(AndLink (PredicateNode "ASPHD2") (PredicateNode "LZTR1")) 
(AndLink (PredicateNode "ATP5L2") (PredicateNode "TXNRD2")) 
(AndLink (PredicateNode "BIK") (PredicateNode "CRYBB2P1")) 
(AndLink (PredicateNode "BRD1") (PredicateNode "MPPED1")) 
(AndLink (PredicateNode "C22orf15") (PredicateNode "CACNA1I")) 
(AndLink (PredicateNode "C22orf15") (PredicateNode "ENTHD1")) 
(AndLink (PredicateNode "C22orf23") (PredicateNode "UPB1")) 
(AndLink (PredicateNode "C22orf31") (PredicateNode "DDX17")) 
(AndLink (PredicateNode "CBX6") (PredicateNode "LARGE")) 
(AndLink (PredicateNode "CBX7") (PredicateNode "MRPL40")) 
(AndLink (PredicateNode "CBX7") (PredicateNode "PIM3")) 
(AndLink (PredicateNode "CBX7") (PredicateNode "SEC14L3")) 
(AndLink (PredicateNode "CCDC117") (PredicateNode "DDX17")) 
(AndLink (PredicateNode "CCDC117") (PredicateNode "NFAM1")) 
(AndLink (PredicateNode "CCT8L2") (PredicateNode "PICK1")) 
(AndLink (PredicateNode "CDPF1") (PredicateNode "TRABD")) 
(AndLink (PredicateNode "CECR6") (PredicateNode "PPP6R2")) 
(AndLink (PredicateNode "CECR6") (PredicateNode "PRODH")) 
(AndLink (PredicateNode "CECR6") (PredicateNode "TFIP11")) 
(AndLink (PredicateNode "CHADL") (PredicateNode "NCAPH2")) 
(AndLink (PredicateNode "COMT") (PredicateNode "SOX10")) 
(PredicateNode "APOBEC3C") 
(PredicateNode "ATP5L2") 
(PredicateNode "ATXN10") 
(PredicateNode "C22orf23") 
(PredicateNode "CBX7") 
(PredicateNode "CECR6") 
(PredicateNode "CHCHD10") 
(PredicateNode "CRYBB1") 
(PredicateNode "CSNK1E") 
(PredicateNode "CYTH4") 
(PredicateNode "DGCR6") 
(PredicateNode "DMC1") 
(PredicateNode "ELFN2") 
(PredicateNode "IFT27") 
(PredicateNode "KIAA0930") 
(PredicateNode "KIAA1671") 
(PredicateNode "LOC648691") 
(PredicateNode "LZTR1") 
(PredicateNode "MAFF") 
(PredicateNode "MGAT3") 
(PredicateNode "MIF") 
(PredicateNode "MPPED1") 
(PredicateNode "NAGA") 
(PredicateNode "NF2") 
(PredicateNode "NFAM1") 
(PredicateNode "OSM") 
(PredicateNode "PANX2") 
(PredicateNode "PDGFB") 
(PredicateNode "PICK1") 
(PredicateNode "RABL2B") 
(PredicateNode "RANBP1") 
(PredicateNode "RBFOX2") 
(PredicateNode "SELM") 
(PredicateNode "SF3A1") 
(PredicateNode "SLC25A17") 
(PredicateNode "SOX10") 
(PredicateNode "TAB1") 
(PredicateNode "TIMP3") 
(PredicateNode "TMEM184B") 
(PredicateNode "TMEM191C") 
(PredicateNode "TMEM211") 
(PredicateNode "TRABD") 
(PredicateNode "UBE2L3") 
(PredicateNode "UPB1") 
(PredicateNode "XRCC6") 
(NotLink (PredicateNode "AAK1")) 
(NotLink (PredicateNode "ABCA12")) 
(NotLink (PredicateNode "ABCG8")) 
(PredicateNode "ADI1") 
(NotLink (PredicateNode "AFF3")) 
(PredicateNode "AGBL5") 
(NotLink (PredicateNode "ALMS1")) 
(NotLink (PredicateNode "ALS2")) 
(NotLink (PredicateNode "ALS2CR11")) 
(NotLink (PredicateNode "AMER3")) 
(NotLink (PredicateNode "ANKAR")) 
(NotLink (PredicateNode "ANKRD36")) 
(NotLink (PredicateNode "ANKRD36BP2")) 
(NotLink (PredicateNode "ARL6IP6")) 
(NotLink (PredicateNode "ARMC9")) 
(NotLink (PredicateNode "ASNSD1")) 
(NotLink (PredicateNode "ATG4B")) 
(PredicateNode "BRE") 
(NotLink (PredicateNode "C2orf54")) 
(NotLink (PredicateNode "C2orf57")) 
(NotLink (PredicateNode "C2orf80")) 
(NotLink (PredicateNode "C2orf83")) 
(PredicateNode "C2orf91") 
(NotLink (PredicateNode "CALCRL")) 
(NotLink (PredicateNode "CAPN10")) 
(PredicateNode "CCDC121") 
(NotLink (PredicateNode "CCDC148")) 
(NotLink (PredicateNode "CCDC93")) 
(NotLink (PredicateNode "CDK15")) 
(NotLink (PredicateNode "CFAP221")) 
(NotLink (PredicateNode "CFAP36")) 
(NotLink (PredicateNode "CHPF")) 
(NotLink (PredicateNode "CKAP2L")) 
(NotLink (PredicateNode "CLHC1")) 
(PredicateNode "CMPK2") 
(NotLink (PredicateNode "CNPPD1")) 
(NotLink (PredicateNode "COL3A1")) 
(PredicateNode "CPSF3") 
(NotLink (PredicateNode "CWC22")) 
(NotLink (PredicateNode "CYP20A1")) 
(PredicateNode "DDX1") 
(NotLink (PredicateNode "DNAH6")) 
(NotLink (PredicateNode "DNAH7")) 
(NotLink (PredicateNode "DNPEP")) 
(NotLink (PredicateNode "DPP10")) 
(PredicateNode "E2F6") 
(NotLink (PredicateNode "ECEL1")) 
(NotLink (PredicateNode "EDAR")) 
(PredicateNode "EHD3") 
(PredicateNode "EIF2AK2") 
(NotLink (PredicateNode "EIF2AK3")) 
(NotLink (PredicateNode "EXOC6B")) 
(PredicateNode "FAM150B") 
(NotLink (PredicateNode "FAM171B")) 
(PredicateNode "FAM84A") 
(NotLink (PredicateNode "FMNL2")) 
(NotLink (PredicateNode "FN1")) 
(PredicateNode "FOSL2") 
(NotLink (PredicateNode "FOXI3")) 
(NotLink (PredicateNode "FSIP2")) 
(NotLink (PredicateNode "GCC2")) 
(NotLink (PredicateNode "GLI2")) 
(NotLink (PredicateNode "GPR148")) 
(PredicateNode "GTF3C2") 
(PredicateNode "HADHA") 
(NotLink (PredicateNode "HDLBP")) 
(NotLink (PredicateNode "IFIH1")) 
(NotLink (PredicateNode "IGFBP2")) 
(NotLink (PredicateNode "ITGA4")) 
(NotLink (PredicateNode "ITGAV")) 
(PredicateNode "KCNF1") 
(PredicateNode "KCNK3") 
(PredicateNode "MYCN") 
(PredicateNode "NDUFAF7") 
(PredicateNode "NRBP1") 
(PredicateNode "ODC1") 
(PredicateNode "PFN4") 
(PredicateNode "PPM1G") 
(PredicateNode "PPP1CB") 
(PredicateNode "PQLC3") 
(PredicateNode "PREB") 
(PredicateNode "PUM2") 
(PredicateNode "RHOB") 
(PredicateNode "SLC8A1") 
(PredicateNode "SPDYA") 
(PredicateNode "SRSF7") 
(PredicateNode "TRMT61B") 
(PredicateNode "UCN") 
(PredicateNode "VSNL1") 
(PredicateNode "WDR43") 
(PredicateNode "YIPF4") 
(PredicateNode "ABCC5") 
(PredicateNode "ACPP") 
(PredicateNode "ACVR2B") 
(PredicateNode "AGTR1") 
(PredicateNode "ALAS1") 
(PredicateNode "ALDH1L1.AS2") 
(PredicateNode "ARF4") 
(PredicateNode "ARL8B") 
(PredicateNode "ATP6V1A") 
(PredicateNode "ATRIP") 
(PredicateNode "BAP1") 
(PredicateNode "C3orf27") 
(PredicateNode "CAMKV") 
(PredicateNode "CCDC51") 
(PredicateNode "CCDC58") 
(PredicateNode "CD96") 
(PredicateNode "CLDND1") 
(PredicateNode "CLRN1") 
(PredicateNode "CMC1") 
(PredicateNode "CMTM7") 
(PredicateNode "CNTN4") 
(PredicateNode "CTDSPL") 
(PredicateNode "CXCR6") 
(PredicateNode "CYB561D2") 
(PredicateNode "DENND6A") 
(PredicateNode "DIRC2") 
(PredicateNode "DPPA2") 
(PredicateNode "DUSP7") 
(PredicateNode "ECT2") 
(PredicateNode "EDEM1") 
(PredicateNode "EIF1B") 
(PredicateNode "EIF4A2") 
(PredicateNode "EIF4E3") 
(PredicateNode "EOGT") 
(PredicateNode "FBXL2") 
(PredicateNode "FBXO45") 
(PredicateNode "FHIT") 
(PredicateNode "FLJ20518") 
(PredicateNode "GCSAM") 
(PredicateNode "GK5") 
(PredicateNode "GNAI2") 
(PredicateNode "GNAT1") 
(PredicateNode "GNB4") 
(PredicateNode "GP5") 
(PredicateNode "GP9") 
(PredicateNode "GPR160") 
(PredicateNode "GPR27") 
(PredicateNode "HES1") 
(PredicateNode "HRH1") 
(PredicateNode "IGF2BP2") 
(PredicateNode "IL12A") 
(PredicateNode "IL1RAP") 
(PredicateNode "IQCF3") 
(PredicateNode "KLF15") 
(PredicateNode "KLHL18") 
(PredicateNode "KLHL24") 
(PredicateNode "KPNA4") 
(PredicateNode "KY") 
(PredicateNode "LHFPL4") 
(PredicateNode "LIPH") 
(PredicateNode "LSAMP") 
(PredicateNode "MANF") 
(PredicateNode "MAPKAPK3") 
(PredicateNode "MB21D2") 
(PredicateNode "METTL6") 
(PredicateNode "MITF") 
(PredicateNode "MON1A") 
(PredicateNode "MRPS25") 
(PredicateNode "MTMR14") 
(PredicateNode "NCK1") 
(PredicateNode "NME6") 
(PredicateNode "NME9") 
(PredicateNode "NR1I2") 
(PredicateNode "NR2C2") 
(PredicateNode "PAK2") 
(PredicateNode "PDHB") 
(PredicateNode "PFKFB4") 
(PredicateNode "PIGX") 
(PredicateNode "PLSCR5") 
(PredicateNode "ABCE1") 
(PredicateNode "ADAD1") 
(PredicateNode "ADH5") 
(PredicateNode "AP1AR") 
(PredicateNode "BLOC1S4") 
(PredicateNode "BMPR1B") 
(PredicateNode "CASP6") 
(PredicateNode "CCNI") 
(PredicateNode "CD38") 
(PredicateNode "CDKL2") 
(PredicateNode "CLDN22") 
(PredicateNode "COMMD8") 
(PredicateNode "CSN2") 
(PredicateNode "CTSO") 
(PredicateNode "DAPP1") 
(PredicateNode "DCUN1D4") 
(PredicateNode "DNAJB14") 
(PredicateNode "DUX4L8") 
(PredicateNode "EPGN") 
(PredicateNode "EXOC1") 
(PredicateNode "FBXW7") 
(PredicateNode "FIP1L1") 
(PredicateNode "G3BP2") 
(PredicateNode "GALNTL6") 
(PredicateNode "GNPDA2") 
(PredicateNode "GNRHR") 
(PredicateNode "GRIA2") 
(PredicateNode "GUCY1A3") 
(PredicateNode "HHIP") 
(PredicateNode "HNRNPD") 
(PredicateNode "ING2") 
(PredicateNode "JAKMIP1") 
(PredicateNode "LIAS") 
(PredicateNode "MAPK10") 
(PredicateNode "METTL14") 
(PredicateNode "MND1") 
(PredicateNode "MOB1B") 
(PredicateNode "MSANTD1") 
(PredicateNode "MSMO1") 
(PredicateNode "MTHFD2L") 
(PredicateNode "MXD4") 
(PredicateNode "NAT8L") 
(PredicateNode "NDUFC1") 
(PredicateNode "NKX3.2") 
(PredicateNode "NKX6.1") 
(PredicateNode "NPY5R") 
(PredicateNode "OCIAD2") 
(PredicateNode "PCDH7") 
(PredicateNode "PDS5A") 
(PredicateNode "PHOX2B") 
(PredicateNode "POLR2B") 
(PredicateNode "PPP2R2C") 
(PredicateNode "PRDM8") 
(PredicateNode "PROL1") 
(PredicateNode "PROM1") 
(PredicateNode "PYURF") 
(PredicateNode "RAB28") 
(PredicateNode "RASL11B") 
(PredicateNode "RHOH") 
(PredicateNode "RPL34") 
(PredicateNode "RPL9") 
(PredicateNode "SLAIN2") 
(PredicateNode "SLC10A4") 
(PredicateNode "SLC10A7") 
(PredicateNode "SLC25A31") 
(PredicateNode "SLC25A4") 
(PredicateNode "SLIT2") 
(PredicateNode "ADRA1B") 
(PredicateNode "AFF4") 
(PredicateNode "ANKRD33B") 
(PredicateNode "AP3S1") 
(PredicateNode "ARHGAP26") 
(PredicateNode "ARRDC3") 
(PredicateNode "ARSI") 
(PredicateNode "ATP6V0E1") 
(PredicateNode "BHMT2") 
(PredicateNode "C1QTNF2") 
(PredicateNode "C5orf15") 
(PredicateNode "C5orf58") 
(PredicateNode "CAMK4") 
(PredicateNode "CCDC112") 
(PredicateNode "CCDC127") 
(PredicateNode "CCL28") 
(PredicateNode "CCNB1") 
(PredicateNode "CCNO") 
(PredicateNode "CD14") 
(PredicateNode "CDH10") 
(PredicateNode "CENPK") 
(PredicateNode "CLK4") 
(PredicateNode "CMBL") 
(PredicateNode "CSNK1G3") 
(PredicateNode "CXCL14") 
(PredicateNode "CXXC5") 
(PredicateNode "DDX46") 
(PredicateNode "DIAPH1") 
(PredicateNode "DRD1") 
(PredicateNode "EBF1") 
(PredicateNode "EFCAB9") 
(PredicateNode "ELOVL7") 
(PredicateNode "FAM153C") 
(PredicateNode "FBLL1") 
(PredicateNode "FBXO4") 
(PredicateNode "FGF1") 
(PredicateNode "GAPT") 
(PredicateNode "GDF9") 
(PredicateNode "GFRA3") 
(PredicateNode "GNB2L1") 
(PredicateNode "GOLPH3") 
(PredicateNode "GRK6") 
(PredicateNode "H2AFY") 
(PredicateNode "HMGCS1") 
(PredicateNode "IL17B") 
(PredicateNode "IL4") 
(PredicateNode "IRX1") 
(PredicateNode "KCNN2") 
(PredicateNode "KIF20A") 
(PredicateNode "KLHL3") 
(PredicateNode "LEAP2") 
(PredicateNode "LMBRD2") 
(PredicateNode "LOC647859") 
(PredicateNode "LRRC70") 
(PredicateNode "LTC4S") 
(PredicateNode "MEF2C") 
(PredicateNode "MIER3") 
(PredicateNode "NDST1") 
(PredicateNode "NDUFS4") 
(PredicateNode "NEUROG1") 
(PredicateNode "NR2F1") 
(PredicateNode "OTULIN") 
(PredicateNode "PAIP1") 
(PredicateNode "PAPD4") 
(PredicateNode "PARP8") 
(PredicateNode "PCDHB12") 
(PredicateNode "PCDHGC3") 
(PredicateNode "PGGT1B") 
(PredicateNode "PLK2") 
(PredicateNode "POU4F3") 
(PredicateNode "PRELID1") 
(PredicateNode "PRR7") 
(PredicateNode "PSD2") 
(PredicateNode "PURA") 
(PredicateNode "RBM27") 
(PredicateNode "REEP2") 
(PredicateNode "RNF145") 
(PredicateNode "RXFP3") 
(PredicateNode "SAR1B") 
(PredicateNode "SCGB3A1") 
(PredicateNode "SEC24A") 
(PredicateNode "SERINC5") 
(PredicateNode "SH3PXD2B") 
(PredicateNode "ABT1") 
(PredicateNode "ADAT2") 
(PredicateNode "AGPAT1") 
(PredicateNode "AKIRIN2") 
(PredicateNode "ALDH8A1") 
(PredicateNode "BAG2") 
(PredicateNode "BCKDHB") 
(PredicateNode "BEND3") 
(PredicateNode "C6orf48") 
(PredicateNode "CD164") 
(PredicateNode "CDC40") 
(PredicateNode "CDK19") 
(PredicateNode "CGA") 
(PredicateNode "DEFB110") 
(PredicateNode "DEFB113") 
(PredicateNode "DEFB114") 
(PredicateNode "DNPH1") 
(PredicateNode "ECHDC1") 
(PredicateNode "FABP7") 
(PredicateNode "FAM26E") 
(PredicateNode "FAM8A1") 
(PredicateNode "FBXO9") 
(PredicateNode "FLOT1") 
(PredicateNode "GCLC") 
(PredicateNode "GNMT") 
(PredicateNode "GSTA1") 
(PredicateNode "GUCA1B") 
(PredicateNode "HIST1H4L") 
(PredicateNode "HS3ST5") 
(PredicateNode "HSD17B8") 
(PredicateNode "IRF4") 
(PredicateNode "KLHDC3") 
(PredicateNode "KPNA5") 
(PredicateNode "LINC00602") 
(PredicateNode "LRRC73") 
(PredicateNode "LTV1") 
(PredicateNode "LY86") 
(PredicateNode "MAP3K7") 
(PredicateNode "MARCKS") 
(PredicateNode "MED23") 
(PredicateNode "MRPL2") 
(PredicateNode "MTHFD1L") 
(PredicateNode "MYB") 
(PredicateNode "NELFE") 
(PredicateNode "NFYA") 
(PredicateNode "NUS1") 
(PredicateNode "PGK2") 
(PredicateNode "PRL") 
(PredicateNode "PRR3") 
(PredicateNode "PRRT1") 
(PredicateNode "RBM24") 
(PredicateNode "RFX6") 
(PredicateNode "RNF5") 
(PredicateNode "RNF8") 
(PredicateNode "RTN4IP1") 
(PredicateNode "RWDD1") 
(PredicateNode "RWDD2A") 
(PredicateNode "RXRB") 
(PredicateNode "SERPINB9") 
(PredicateNode "SLC22A23") 
(PredicateNode "SLC35A1") 
(PredicateNode "SLC35B3") 
(PredicateNode "SMIM13") 
(PredicateNode "SMIM8") 
(PredicateNode "SPACA1") 
(PredicateNode "STX7") 
(PredicateNode "TBPL1") 
(PredicateNode "TCP1") 
(PredicateNode "TFAP2A") 
(PredicateNode "TFAP2B") 
(PredicateNode "TFB1M") 
(PredicateNode "TMEM14A") 
(PredicateNode "TMEM151B") 
(PredicateNode "TMEM200A") 
(PredicateNode "ACTL6B") 
(PredicateNode "AHCYL2") 
(PredicateNode "AIMP2") 
(PredicateNode "ARHGEF35") 
(PredicateNode "ASB4") 
(PredicateNode "ASL") 
(PredicateNode "BAIAP2L1") 
(PredicateNode "BCL7B") 
(PredicateNode "BRAF") 
(PredicateNode "BZW2") 
(PredicateNode "C7orf26") 
(PredicateNode "C7orf61") 
(PredicateNode "C7orf76") 
(PredicateNode "CASD1") 
(PredicateNode "CCDC126") 
(PredicateNode "CD36") 
(PredicateNode "CDK14") 
(PredicateNode "CEP41") 
(PredicateNode "CLDN4") 
(PredicateNode "CLEC2L") 
(PredicateNode "CLEC5A") 
(PredicateNode "CNPY4") 
(PredicateNode "COPG2") 
(PredicateNode "CPA2") 
(PredicateNode "DGKB") 
(PredicateNode "DNAJC2") 
(PredicateNode "DYNC1I1") 
(PredicateNode "EPO") 
(PredicateNode "EVX1") 
(PredicateNode "FAM126A") 
(PredicateNode "FEZF1") 
(PredicateNode "FIS1") 
(PredicateNode "FKBP14") 
(PredicateNode "FKBP6") 
(PredicateNode "FSCN1") 
(PredicateNode "GBAS") 
(PredicateNode "GBX1") 
(PredicateNode "GCK") 
(PredicateNode "GIMAP1") 
(PredicateNode "GLCCI1") 
(PredicateNode "GNB2") 
(PredicateNode "GPR141") 
(PredicateNode "GPR22") 
(PredicateNode "GRB10") 
(PredicateNode "GTF2IRD2B") 
(PredicateNode "HEPACAM2") 
(PredicateNode "HIBADH") 
(PredicateNode "HNRNPA2B1") 
(PredicateNode "HOXA11") 
(PredicateNode "HOXA5") 
(PredicateNode "HOXA6") 
(PredicateNode "HSPB1") 
(PredicateNode "HUS1") 
(PredicateNode "INHBA") 
(PredicateNode "INSIG1") 
(PredicateNode "ITGB8") 
(PredicateNode "KBTBD2") 
(PredicateNode "KCND2") 
(PredicateNode "KIAA1147") 
(PredicateNode "KRIT1") 
(PredicateNode "LINC00174") 
(PredicateNode "LOC441242") 
(PredicateNode "LOC493754") 
(PredicateNode "MDFIC") 
(PredicateNode "MEPCE") 
(PredicateNode "MIOS") 
(PredicateNode "MTRNR2L6") 
(PredicateNode "MYL10") 
(PredicateNode "MYL7") 
(PredicateNode "NAMPT") 
(PredicateNode "NCF1C") 
(PredicateNode "NSUN5") 
(PredicateNode "OR6W1P") 
(PredicateNode "PRKAR2B") 
(PredicateNode "PRSS1") 
(PredicateNode "PTN") 
(PredicateNode "PURB") 
(PredicateNode "RALA") 
(PredicateNode "RASA4") 
(PredicateNode "AGO2") 
(PredicateNode "ANKRD46") 
(PredicateNode "AP3M2") 
(PredicateNode "ARC") 
(PredicateNode "BOP1") 
(PredicateNode "BRF2") 
(PredicateNode "C8orf33") 
(PredicateNode "C8orf44.SGK3") 
(PredicateNode "C8orf88") 
(PredicateNode "CHMP7") 
(PredicateNode "CHRNA6") 
(PredicateNode "CLN8") 
(PredicateNode "COPS5") 
(PredicateNode "DCTN6") 
(PredicateNode "DEFA1B") 
(PredicateNode "DPYSL2") 
(PredicateNode "EBAG9") 
(PredicateNode "EIF4EBP1") 
(PredicateNode "EMC2") 
(PredicateNode "FABP9") 
(PredicateNode "FAM150A") 
(PredicateNode "FBXO43") 
(PredicateNode "FGF20") 
(PredicateNode "FSBP") 
(PredicateNode "GDF6") 
(PredicateNode "GRINA") 
(PredicateNode "GSR") 
(PredicateNode "HGH1") 
(PredicateNode "HMBOX1") 
(PredicateNode "HOOK3") 
(PredicateNode "KBTBD11") 
(PredicateNode "KCNB2") 
(PredicateNode "LRRC14") 
(PredicateNode "LY6H") 
(PredicateNode "LYNX1") 
(PredicateNode "MMP16") 
(PredicateNode "MRPL13") 
(PredicateNode "NDRG1") 
(PredicateNode "NECAB1") 
(PredicateNode "NKX6.3") 
(PredicateNode "NPM2") 
(PredicateNode "OPRK1") 
(PredicateNode "OR4F21") 
(PredicateNode "OXR1") 
(PredicateNode "PI15") 
(PredicateNode "PPAPDC1B") 
(PredicateNode "PPP1R16A") 
(PredicateNode "PPP2CB") 
(PredicateNode "PPP3CC") 
(PredicateNode "PURG") 
(PredicateNode "RAD21") 
(PredicateNode "RALYL") 
(PredicateNode "REXO1L2P") 
(PredicateNode "RGS20") 
(PredicateNode "RGS22") 
(PredicateNode "RNF139") 
(PredicateNode "SMIM18") 
(PredicateNode "SOX17") 
(PredicateNode "SPAG11B") 
(PredicateNode "SPIDR") 
(PredicateNode "STAR") 
(PredicateNode "STK3") 
(PredicateNode "TATDN1") 
(PredicateNode "THAP1") 
(PredicateNode "TMEM64") 
(PredicateNode "TMEM74") 
(PredicateNode "TP53INP1") 
(PredicateNode "TRIB1") 
(PredicateNode "TRPS1") 
(PredicateNode "TSTA3") 
(PredicateNode "UBE2V2") 
(PredicateNode "ADAMTSL2") 
(PredicateNode "AK3") 
(PredicateNode "ALDOB") 
(PredicateNode "ARPC5L") 
(PredicateNode "ASS1") 
(PredicateNode "B4GALT1") 
(PredicateNode "BARHL1") 
(PredicateNode "C9orf152") 
(PredicateNode "C9orf153") 
(PredicateNode "C9orf16") 
(PredicateNode "C9orf53") 
(PredicateNode "C9orf64") 
(PredicateNode "C9orf91") 
(PredicateNode "CCL19") 
(PredicateNode "CDC37L1") 
(PredicateNode "DIRAS2") 
(PredicateNode "DOLPP1") 
(PredicateNode "EQTN") 
(PredicateNode "ERP44") 
(PredicateNode "FAM122A") 
(PredicateNode "FAM129B") 
(PredicateNode "FAM78A") 
(PredicateNode "FIBCD1") 
(PredicateNode "FOXB2") 
(PredicateNode "FOXD4L5") 
(PredicateNode "FOXE1") 
(PredicateNode "FUBP3") 
(PredicateNode "FXN") 
(PredicateNode "GAS1") 
(PredicateNode "GRHPR") 
(PredicateNode "GRIN1") 
(PredicateNode "GTF3C4") 
(PredicateNode "HABP4") 
(PredicateNode "IFNA2") 
(PredicateNode "IFNA5") 
(PredicateNode "IL33") 
(PredicateNode "INSL4") 
(PredicateNode "KGFLP2") 
(PredicateNode "KIAA1045") 
(PredicateNode "KLF4") 
(PredicateNode "KLF9") 
(PredicateNode "LCN1") 
(PredicateNode "LCN6") 
(PredicateNode "LHX2") 
(PredicateNode "LHX6") 
(PredicateNode "LMX1B") 
(PredicateNode "LOC158434") 
(PredicateNode "MAPKAP1") 
(PredicateNode "MRPL41") 
(PredicateNode "MSMP") 
(PredicateNode "NAIF1") 
(PredicateNode "NFIL3") 
(PredicateNode "NPR2") 
(PredicateNode "NR6A1") 
(PredicateNode "NRARP") 
(PredicateNode "NXNL2") 
(PredicateNode "ORM2") 
(PredicateNode "PALM2") 
(PredicateNode "PDCL") 
(PredicateNode "PHF19") 
(PredicateNode "PIP5KL1") 
(PredicateNode "PLAA") 
(PredicateNode "PPP3R2") 
(PredicateNode "PRDM12") 
(PredicateNode "PRPF4") 
(PredicateNode "PSIP1") 
(PredicateNode "PTAR1") 
(PredicateNode "PTGES") 
(PredicateNode "PTRH1") 
(PredicateNode "RAB14") 
(PredicateNode "RFX3") 
(PredicateNode "RGP1") 
(PredicateNode "RNF208") 
(PredicateNode "RNF38") 
(PredicateNode "SEC61B") 
(PredicateNode "SHB") 
(PredicateNode "SLC25A25") 
(PredicateNode "SPIN1") 
(PredicateNode "ABCD1") 
(PredicateNode "ACSL4") 
(PredicateNode "AP1S2") 
(PredicateNode "APEX2") 
(PredicateNode "APLN") 
(PredicateNode "ARAF") 
(PredicateNode "ARHGEF6") 
(PredicateNode "ARMCX3") 
(PredicateNode "ARX") 
(PredicateNode "AWAT1") 
(PredicateNode "AWAT2") 
(PredicateNode "BCAP31") 
(PredicateNode "BEX2") 
(PredicateNode "CA5B") 
(PredicateNode "CASK") 
(PredicateNode "CDK16") 
(PredicateNode "CHIC1") 
(PredicateNode "CHRDL1") 
(PredicateNode "CLCN5") 
(PredicateNode "COX7B") 
(PredicateNode "CSTF2") 
(PredicateNode "CT45A2") 
(PredicateNode "CT55") 
(PredicateNode "CTPS2") 
(PredicateNode "CUL4B") 
(PredicateNode "CXCR3") 
(PredicateNode "CXorf23") 
(PredicateNode "CXorf40B") 
(PredicateNode "CXorf57") 
(PredicateNode "CYSLTR1") 
(PredicateNode "DDX26B") 
(PredicateNode "ELF4") 
(PredicateNode "ELK1") 
(PredicateNode "ERAS") 
(PredicateNode "FAM122B") 
(PredicateNode "FAM223B") 
(PredicateNode "FIGF") 
(PredicateNode "FOXO4") 
(PredicateNode "FOXP3") 
(PredicateNode "G6PD") 
(PredicateNode "GPR34") 
(PredicateNode "GPR64") 
(PredicateNode "H2AFB3") 
(PredicateNode "HTATSF1") 
(PredicateNode "IDS") 
(PredicateNode "IKBKG") 
(PredicateNode "IL1RAPL1") 
(PredicateNode "KLHL13") 
(PredicateNode "KLHL4") 
(PredicateNode "LINC00632") 
(PredicateNode "LOC100132831") 
(PredicateNode "LOC100288814") 
(PredicateNode "LONRF3") 
(PredicateNode "LRCH2") 
(PredicateNode "MAGEB1") 
(PredicateNode "MAGEH1") 
(PredicateNode "MAGT1") 
(PredicateNode "MAOB") 
(PredicateNode "MBNL3") 
(PredicateNode "MED12") 
(PredicateNode "MID1IP1") 
(PredicateNode "MPP1") 
(PredicateNode "NDP") 
(PredicateNode "NDUFB11") 
(PredicateNode "NKRF") 
(PredicateNode "NONO") 
(PredicateNode "NSDHL") 
(PredicateNode "NUDT10") 
(PredicateNode "NUDT11") 
(PredicateNode "NXF2") 
(PredicateNode "NXF3") 
(PredicateNode "OCRL") 
(PredicateNode "OTUD5") 
(PredicateNode "P2RY10") 
(PredicateNode "PCSK1N") 
(PredicateNode "PDK3") 
(PredicateNode "PGRMC1") 
(PredicateNode "PPP1R2P9") 
(PredicateNode "PPP1R3F") 
(PredicateNode "PRICKLE3") 
(PredicateNode "PRPS1") 
(PredicateNode "PRPS2") 
(set! count (count-all))
(display count)
(display message)
(define end_time (current-time))
(define elapsed_time (/ (- end_time start_time) 60.0))
(display "Atom loading End in ..")
(display elapsed_time)
(display " minutes\n")
