scm
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_000") (PredicateNode "ADORA2A") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_000") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_000") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_001") (PredicateNode "ADRBK2") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_001") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_001") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_002") (AndLink (PredicateNode "A4GALT") (PredicateNode "CHEK2")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_002") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_002") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_003") (AndLink (PredicateNode "ACO2") (PredicateNode "MAPK12")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_003") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_003") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_004") (AndLink (PredicateNode "ADRBK2") (PredicateNode "AP1B1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_004") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_004") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_005") (AndLink (PredicateNode "AIFM3") (PredicateNode "SLC25A17")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_005") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_005") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_006") (AndLink (PredicateNode "AIFM3") (PredicateNode "TMEM184B")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_006") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_006") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_007") (AndLink (PredicateNode "ALG12") (PredicateNode "GGT1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_007") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_007") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_008") (AndLink (PredicateNode "ANKRD54") (PredicateNode "GGA1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_008") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_008") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_009") (AndLink (PredicateNode "APOBEC3C") (PredicateNode "ELFN2")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_009") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_009") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_010") (AndLink (PredicateNode "APOBEC3C") (PredicateNode "KCTD17")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_010") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_010") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_011") (AndLink (PredicateNode "APOBEC3D") (PredicateNode "NCAPH2")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_011") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_011") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_012") (AndLink (PredicateNode "APOBEC3G") (PredicateNode "CRYBB1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_012") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_012") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_013") (AndLink (PredicateNode "APOBEC3G") (PredicateNode "PI4KA")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_013") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_013") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_014") (AndLink (PredicateNode "ARFGAP3") (PredicateNode "RANBP1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_014") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_014") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_015") (AndLink (PredicateNode "ARSA") (PredicateNode "OSM")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_015") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_015") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_016") (AndLink (PredicateNode "ASPHD2") (PredicateNode "LZTR1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_016") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_016") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_017") (AndLink (PredicateNode "ATP5L2") (PredicateNode "TXNRD2")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_017") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_017") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_018") (AndLink (PredicateNode "BIK") (PredicateNode "CRYBB2P1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_018") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_018") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_019") (AndLink (PredicateNode "BRD1") (PredicateNode "MPPED1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_019") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_019") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_020") (AndLink (PredicateNode "C22orf15") (PredicateNode "CACNA1I")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_020") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_020") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_021") (AndLink (PredicateNode "C22orf15") (PredicateNode "ENTHD1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_021") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_021") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_022") (AndLink (PredicateNode "C22orf23") (PredicateNode "UPB1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_022") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_022") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_023") (AndLink (PredicateNode "C22orf31") (PredicateNode "DDX17")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_023") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_023") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_024") (AndLink (PredicateNode "CBX6") (PredicateNode "LARGE")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_024") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_024") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_025") (AndLink (PredicateNode "CBX7") (PredicateNode "MRPL40")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_025") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_025") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_026") (AndLink (PredicateNode "CBX7") (PredicateNode "PIM3")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_026") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_026") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_027") (AndLink (PredicateNode "CBX7") (PredicateNode "SEC14L3")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_027") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_027") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_028") (AndLink (PredicateNode "CCDC117") (PredicateNode "DDX17")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_028") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_028") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_029") (AndLink (PredicateNode "CCDC117") (PredicateNode "NFAM1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_029") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_029") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_030") (AndLink (PredicateNode "CCT8L2") (PredicateNode "PICK1")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_030") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_030") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_031") (AndLink (PredicateNode "CDPF1") (PredicateNode "TRABD")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_031") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_031") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_032") (AndLink (PredicateNode "CECR6") (PredicateNode "PPP6R2")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_032") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_032") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_033") (AndLink (PredicateNode "CECR6") (PredicateNode "PRODH")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_033") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_033") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_034") (AndLink (PredicateNode "CECR6") (PredicateNode "TFIP11")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_034") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_034") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_035") (AndLink (PredicateNode "CHADL") (PredicateNode "NCAPH2")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_035") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_035") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_036") (AndLink (PredicateNode "COMT") (PredicateNode "SOX10")) )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_036") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_036") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_037") (PredicateNode "APOBEC3C") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_037") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_037") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_038") (PredicateNode "ATP5L2") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_038") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_038") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_039") (PredicateNode "ATXN10") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_039") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_039") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_040") (PredicateNode "C22orf23") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_040") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_040") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_041") (PredicateNode "CBX7") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_041") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_041") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_042") (PredicateNode "CECR6") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_042") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_042") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_043") (PredicateNode "CHCHD10") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_043") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_043") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_044") (PredicateNode "CRYBB1") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_044") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_044") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_045") (PredicateNode "CSNK1E") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_045") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_045") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_046") (PredicateNode "CYTH4") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_046") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_046") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_047") (PredicateNode "DGCR6") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_047") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_047") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_048") (PredicateNode "DMC1") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_048") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_048") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_049") (PredicateNode "ELFN2") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_049") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_049") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_050") (PredicateNode "IFT27") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_050") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_050") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_051") (PredicateNode "KIAA0930") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_051") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_051") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_052") (PredicateNode "KIAA1671") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_052") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_052") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_053") (PredicateNode "LOC648691") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_053") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_053") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_054") (PredicateNode "LZTR1") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_054") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_054") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_055") (PredicateNode "MAFF") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_055") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_055") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_056") (PredicateNode "MGAT3") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_056") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_056") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_057") (PredicateNode "MIF") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_057") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_057") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_058") (PredicateNode "MPPED1") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_058") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_058") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_059") (PredicateNode "NAGA") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_059") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_059") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_060") (PredicateNode "NF2") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_060") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_060") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_061") (PredicateNode "NFAM1") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_061") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_061") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_062") (PredicateNode "OSM") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_062") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_062") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_063") (PredicateNode "PANX2") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_063") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_063") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_064") (PredicateNode "PDGFB") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_064") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_064") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_065") (PredicateNode "PICK1") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_065") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_065") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_066") (PredicateNode "RABL2B") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_066") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_066") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_067") (PredicateNode "RANBP1") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_067") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_067") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_068") (PredicateNode "RBFOX2") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_068") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_068") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_069") (PredicateNode "SELM") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_069") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_069") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_070") (PredicateNode "SF3A1") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_070") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_070") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_071") (PredicateNode "SLC25A17") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_071") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_071") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_072") (PredicateNode "SOX10") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_072") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_072") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_073") (PredicateNode "TAB1") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_073") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_073") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_074") (PredicateNode "TIMP3") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_074") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_074") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_075") (PredicateNode "TMEM184B") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_075") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_075") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_076") (PredicateNode "TMEM191C") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_076") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_076") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_077") (PredicateNode "TMEM211") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_077") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_077") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_078") (PredicateNode "TRABD") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_078") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_078") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_079") (PredicateNode "UBE2L3") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_079") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_079") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_080") (PredicateNode "UPB1") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_080") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_080") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_081") (PredicateNode "XRCC6") )
(EvaluationLink (stv 1 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_081") (PredicateNode "aging")))
(EvaluationLink (stv 1 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_081") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_082") (PredicateNode "ACO2") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_082") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_082") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_083") (AndLink (PredicateNode "ACO2") (PredicateNode "MKL1")) )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_083") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_083") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_084") (AndLink (PredicateNode "ADM2") (PredicateNode "ZDHHC8P1")) )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_084") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_084") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_085") (AndLink (PredicateNode "ADSL") (PredicateNode "EIF4ENIF1")) )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_085") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_085") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_086") (AndLink (PredicateNode "ANKRD54") (PredicateNode "PRR14L")) )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_086") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_086") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_087") (AndLink (PredicateNode "APOBEC3D") (PredicateNode "MOV10L1")) )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_087") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_087") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_088") (AndLink (PredicateNode "APOBEC3D") (PredicateNode "SRRD")) )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_088") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_088") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_089") (AndLink (PredicateNode "APOL5") (PredicateNode "FAM227A")) )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_089") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_089") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_090") (AndLink (PredicateNode "C22orf29") (PredicateNode "GATSL3")) )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_090") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_090") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_091") (AndLink (PredicateNode "C22orf29") (PredicateNode "SERHL2")) )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_091") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_091") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_092") (AndLink (PredicateNode "C22orf29") (PredicateNode "TSSK2")) )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_092") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_092") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_093") (AndLink (PredicateNode "CBX6") (PredicateNode "HDAC10")) )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_093") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_093") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_094") (AndLink (PredicateNode "CRYBA4") (PredicateNode "DERL3")) )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_094") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_094") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_095") (PredicateNode "APOBEC3D") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_095") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_095") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_096") (PredicateNode "C22orf15") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_096") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_096") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_097") (PredicateNode "CHADL") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_097") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_097") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_098") (PredicateNode "CHEK2") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_098") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_098") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_099") (PredicateNode "CRYBA4") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_099") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_099") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_100") (PredicateNode "DDX17") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_100") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_100") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_101") (PredicateNode "HIRA") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_101") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_101") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_102") (PredicateNode "NCAPH2") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_102") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_102") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_103") (PredicateNode "NIPSNAP1") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_103") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_103") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_104") (PredicateNode "NPTXR") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_104") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_104") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_105") (PredicateNode "PACSIN2") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_105") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_105") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_106") (PredicateNode "PATZ1") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_106") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_106") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_107") (PredicateNode "PDXP") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_107") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_107") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_108") (PredicateNode "PLA2G6") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_108") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_108") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_109") (PredicateNode "RNF185") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_109") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_109") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_110") (PredicateNode "RTN4R") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_110") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_110") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_111") (PredicateNode "SNAP29") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_111") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_111") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_112") (PredicateNode "TFIP11") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_112") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_112") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_113") (NotLink (PredicateNode "TMEM191B")) )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_113") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_113") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_114") (PredicateNode "TUBA8") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_114") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_114") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_115") (PredicateNode "VPREB3") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_115") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_115") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_116") (PredicateNode "ZC3H7B") )
(EvaluationLink (stv .9850746268656716 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_116") (PredicateNode "aging")))
(EvaluationLink (stv 0.99 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_116") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_117") (PredicateNode "ADSL") )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_117") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_117") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_118") (AndLink (PredicateNode "ADSL") (PredicateNode "APOL3")) )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_118") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_118") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_119") (AndLink (PredicateNode "ADSL") (PredicateNode "BCR")) )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_119") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_119") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_120") (AndLink (PredicateNode "ADSL") (PredicateNode "PRR5.ARHGAP8")) )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_120") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_120") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_121") (AndLink (PredicateNode "APOL1") (PredicateNode "TBC1D22A")) )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_121") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_121") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_122") (AndLink (PredicateNode "APOL5") (PredicateNode "C22orf31")) )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_122") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_122") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_123") (AndLink (PredicateNode "ARVCF") (PredicateNode "SEPT5.GP1BB")) )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_123") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_123") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_124") (AndLink (PredicateNode "C22orf31") (PredicateNode "SEC14L6")) )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_124") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_124") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_125") (AndLink (PredicateNode "CBX6") (PredicateNode "KREMEN1")) )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_125") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_125") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_126") (PredicateNode "ANKRD54") )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_126") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_126") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_127") (PredicateNode "C22orf31") )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_127") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_127") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_128") (PredicateNode "FAM227A") )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_128") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_128") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_129") (PredicateNode "GALR3") )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_129") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_129") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_130") (PredicateNode "GGA1") )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_130") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_130") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_131") (PredicateNode "GSTT1") )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_131") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_131") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_132") (PredicateNode "LINC00896") )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_132") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_132") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_133") (PredicateNode "RANGAP1") )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_133") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_133") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_134") (PredicateNode "SEPT5.GP1BB") )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_134") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_134") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_135") (PredicateNode "SGSM3") )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_135") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_135") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_136") (PredicateNode "TANGO2") )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_136") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_136") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_137") (PredicateNode "TBC1D22A") )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_137") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_137") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_138") (PredicateNode "UQCR10") )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_138") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_138") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_139") (PredicateNode "ZNF70") )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_139") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_139") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_140") (PredicateNode "ZNRF3") )
(EvaluationLink (stv .9701492537313433 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_140") (PredicateNode "aging")))
(EvaluationLink (stv 0.98 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_140") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_141") (AndLink (PredicateNode "ACR") (PredicateNode "MFNG")) )
(EvaluationLink (stv .9552238805970149 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_141") (PredicateNode "aging")))
(EvaluationLink (stv 0.97 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_141") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_142") (AndLink (PredicateNode "BIK") (PredicateNode "PARVG")) )
(EvaluationLink (stv .9552238805970149 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_142") (PredicateNode "aging")))
(EvaluationLink (stv 0.97 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_142") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_143") (AndLink (PredicateNode "C22orf46") (PredicateNode "SYCE3")) )
(EvaluationLink (stv .9552238805970149 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_143") (PredicateNode "aging")))
(EvaluationLink (stv 0.97 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_143") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_144") (PredicateNode "BIK") )
(EvaluationLink (stv .9552238805970149 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_144") (PredicateNode "aging")))
(EvaluationLink (stv 0.97 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_144") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_145") (PredicateNode "CDC42EP1") )
(EvaluationLink (stv .9552238805970149 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_145") (PredicateNode "aging")))
(EvaluationLink (stv 0.97 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_145") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_146") (PredicateNode "DGCR6L") )
(EvaluationLink (stv .9552238805970149 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_146") (PredicateNode "aging")))
(EvaluationLink (stv 0.97 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_146") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_147") (PredicateNode "GGT1") )
(EvaluationLink (stv .9552238805970149 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_147") (PredicateNode "aging")))
(EvaluationLink (stv 0.97 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_147") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_148") (PredicateNode "KIAA1644") )
(EvaluationLink (stv .9552238805970149 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_148") (PredicateNode "aging")))
(EvaluationLink (stv 0.97 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_148") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_149") (PredicateNode "LARGE") )
(EvaluationLink (stv .9552238805970149 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_149") (PredicateNode "aging")))
(EvaluationLink (stv 0.97 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_149") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_150") (PredicateNode "MFNG") )
(EvaluationLink (stv .9552238805970149 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_150") (PredicateNode "aging")))
(EvaluationLink (stv 0.97 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_150") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_151") (PredicateNode "SDF2L1") )
(EvaluationLink (stv .9552238805970149 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_151") (PredicateNode "aging")))
(EvaluationLink (stv 0.97 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_151") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_152") (PredicateNode "SLC35E4") )
(EvaluationLink (stv .9402985074626866 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_152") (PredicateNode "aging")))
(EvaluationLink (stv 0.96 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_152") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_153") (PredicateNode "MTMR3") )
(EvaluationLink (stv .9253731343283582 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_153") (PredicateNode "aging")))
(EvaluationLink (stv 0.95 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_153") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_154") (PredicateNode "ADM2") )
(EvaluationLink (stv .9104477611940299 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_154") (PredicateNode "aging")))
(EvaluationLink (stv 0.94 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_154") (PredicateNode "aging")))
(EquivalenceLink (stv 1.0 1.0) (PredicateNode "chr22_moses.5x10.csv:moses_model_155") (PredicateNode "ASPHD2") )
(EvaluationLink (stv .865671641791045 1) (PredicateNode "accuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_155") (PredicateNode "aging")))
(EvaluationLink (stv 0.91 1) (PredicateNode "balancedAccuracy") (ListLink (PredicateNode "chr22_moses.5x10.csv:moses_model_155") (PredicateNode "aging")))
